[variables]
NIXPACKS_NODE_VERSION = "22"
NIXPACKS_PHP_VERSION = "8.4"

# 1. Paksa NPM menginstal devDependencies untuk keperluan compile
[phases.install]
cmds = [
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "composer install --ignore-platform-reqs",
  "npm i --include=dev"
]

# 2. Siapkan database SQLite, atur permission, jalankan migrasi, dan jalankan server pada saat startup
[phases.start]
cmd = "mkdir -p /app/database && touch /app/database/database.sqlite && chmod -R 777 /app/database && php artisan migrate --force && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
